exports.CATEGORIES = {
  software: [],
  tech: [],
  development: [
    "frontend development",
    "backend development",
    "full stack development",
    "mobile app development",
  ],
  "programming languages": ["javascript", "python", "dart"],
  "frameworks & libraries": [
    "flutter",
    "react",
    "next.js",
    "node.js",
    "express",
    "mongoose",
    "redux",
    "framer-motion",
    "aceternity ui",
  ],
  "operating systems": [
    "linux",
    "server",
    "windows",
    "macos",
    "android",
    "ios",
  ],
  "artificial intelligence": [],
  database: ["mongodb", "firebase"],
  "cyber security": [],
  mobile: ["android", "ios"],
  design: [],
};
